### ISSUE TITLE
Intellisense enhancement ideas

### ISSUE THREAD

**Issue by Siphonophora** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#1]
@theron-wang Thanks for putting this together. I was very happy to see this the other day. 

Wanted to give a pair of QOL suggestions for intellisense:
* Being fairly new to tailwind, having intellisense do a contains search, instead of starts with, would be great.
* Sorting would be nice to have `bg-red-50` sort before `bg-red-100`.

**Comment by theron-wang** [comment]
Thank you for your feedback!

I've just released an update which addresses all of your suggestions. Feel free to check it out and let me know if you encounter any more problems!
