### ISSUE TITLE
OutputCssFile becomes null if file is missing.

### ISSUE THREAD

**Issue by Siphonophora** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#11]
Hi, i'm running into an issue with the extension, if the output file is not present at build start. When the file is not there, then the extension is changing output css file to null, when it starts the build. 

I would expect it should not clear the output file config, and instead just rebuild that file. 

If it helps, this is the file I am starting with. `{"ConfigurationFile":"tailwind.config.js","InputCssFile":"Styles\\site_src.css","OutputCssFile":"wwwroot\\css\\site.css"}`

**Comment by theron-wang** [comment]
I just released an update which addresses the issue. Hopefully, everything works as expected now.

Thanks!

**Comment by Siphonophora** [comment]
@theron-wang On 1.1.7.3 I think this is only partly fixed. If the output file isn't present, the config no longer gets nulled. However, it seems to still be falling back on the default output file instead of the configured one, when it builds.

**Comment by theron-wang** [comment]
Sorry for the incomplete fix! I'll look into it and release a fix.

**Comment by theron-wang** [comment]
I found that when you directly modify the `tailwind.extension.json` file, the build process fails to pick up on the changes -- I added an event listener so it correctly updates when that file is saved.

Again, sorry for the oversight in the previous fix, and I hope this works well.
