### ISSUE TITLE
[Feature Request] Support for `Class=""` in Razor Components.

### ISSUE THREAD

**Issue by ApacheTech** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#12]
Would it be possible to add support for Blazor components that use `Class=""` as a parameter?

You constrain it to lowercase `class=` only, here: https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/blob/main/src/Completions/Controllers/RazorCompletionController.cs#L165

A `.ToLowerInvariant()` on line 163 should be ok to fix it.

**Comment by theron-wang** [comment]
I just included this in 1.1.7.6 along with the other bug fixes. Thanks for the suggestion!
