### ISSUE TITLE
Extension Tailwind Build Process constantly turning itself on

### ISSUE THREAD

**Issue by BowserKingKoopa** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#18]
The Extension's built in Tailwind Build Process is constantly and aggressively turning itself on. I don't use this build process and I'm constantly fighting with the extension to turn it off. I turn it off with the menu item under the Visual Studio Build menu. But it always just turns itself on at some point.  Sometimes right away, sometimes it waits a while to lull me into a false sense of security. I don't know what turns it back on, it feels random. Can you help me get this thing to stay off?

**Comment by theron-wang** [comment]
It turns on every time you build the project. If you don’t use the build
process you can disable it in Tools > Options > TailwindCSSIntellisense and
set the build process to “None”.

**Comment by BowserKingKoopa** [comment]
Awesome, thank you.  I had thought it had started with a recent update but maybe I just didn't notice it before.

**Comment by BowserKingKoopa** [comment]
Awesome. Thank you.
