### ISSUE TITLE
项目所在目录不能使用中文

### ISSUE THREAD

**Issue by jiachunhui** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#21]
项目如果放在中文目录下，插件获取不到配置文件，从日志中显示，获取配置文件目录乱码

**Comment by jiachunhui** [comment]
我尝试把目录换到非中文，运行正常

**Comment by theron-wang** [comment]
I’m sorry, but do you think you could provide some steps to reproduce the issue in English? I have a vague understanding of what you mean but I want to make sure I am not misunderstanding this.

**Comment by jiachunhui** [comment]
我再次尝试发现正常，目录使用中文也可以，真是不好意思，上面遇到的问题，是我在之前项目中，项目中已经存在Tailwind 配置文件，我再使用看看

**Comment by theron-wang** [comment]
Great! I will mark this as closed then. If the issue arises again, feel free to comment here again and I will reopen this :)
