### ISSUE TITLE
New file extension?

### ISSUE THREAD

**Issue by TheXenocide** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#27]
Would it be feasible to make `.tcss` files (or some such) recognized as Tailwind CSS files for highlighting/auto-complete in VS? It's not the end of the world if not, but it would help simplify some things for me. Maybe it might help with getting rid of the extraneous error lines too?

I'm hoping to not use `.css` for the pre-processed files so that I can process them into the same filename (but changed to `.css`) at the same path. This is, in-part, so that I can do the same thing with Tailwind that I can do with Sass for Blazor component-level CSS isolation, which would hopefully look something like:

- NavMenu.razor
  - NavMenu.razor.tcss (Tailwind CSS)
  - NavMenu.razor.css (Generated)

I actually plan to do the Tailwind compilation in MSBuild without this extension (for CI purposes and such), hopefully using the CLI so there's no dependency on NPM (this is the only feature dependent on it in my project currently). I was able to set the build type to None, which works great for my needs, now my only issue is that Blazor wants the component level css files to have very specific filenames. I think for now I'll try something like `*.tw.css` or something like that but figured it couldn't hurt to ask.

**Comment by theron-wang** [comment]
Yep! I just added IntelliSense for `.tcss` files. Thanks for the suggestion!

**Comment by TheXenocide** [comment]
Awesome, thanks!
