### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by skttl** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#28]
Would be nice if the plugin could lint like the official vs code extension.

Eg. if I have `<div class="lg:h-[634px] mt-26 mb-12 lg:mb-24 relative absolute">` I want it to put green squigglies below `relative` and `absolute`.

**Comment by theron-wang** [comment]
Sorry for the late response. I just added linting, so you should be able to use it once you update the extension.

Thanks for the suggestion!

**Comment by skttl** [comment]
This is great - thanks!
