### ISSUE TITLE
Cleanup / class sorting

### ISSUE THREAD

**Issue by skttl** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#29]
Would love a feature where you could either select a class list, and have the plugin sort the classes (like sort selection in the offical VS code plugin).

Or automatically sort all class lists on save like the [Headwind extension for VS Code](https://marketplace.visualstudio.com/items?itemName=heybourn.headwind)

**Comment by theron-wang** [comment]
Sorry about the delay! Just added in 1.3.0. Thank you for the suggestion!

**Comment by skttl** [comment]
Fantastic news! Can't wait to try it out - thanks for all your hard work!
