### ISSUE TITLE
This doesn't work with typescript?

### ISSUE THREAD

**Issue by tngflx** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#34]
Hi is typescript not supported at all? I saw the definition for tailwind.config.js only include js files

**Comment by theron-wang** [comment]
Typescript files are not supported in the solution explorer context menu.
However, if your configuration file is a typescript file, you can find the
tailwind.extension.json file in your project root and specify the path in
there.

**Comment by theron-wang** [comment]
Sorry about the late response, but TypeScript files should now be able to be used as configuration files. Thanks for the report!
