### ISSUE TITLE
Support for VS2022 ARM

### ISSUE THREAD

**Issue by dchelstowski** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#37]
Hello!

I'm using VS2022 with Parallels (virtualized in coherence mode) on my Macbook, which is installed in version ARM. Is there any possibility to have a support for this extension with ARM versions? It says that it cannot be installed on any installed VS versions - I believe it is caused because of ARM version. 

Many thanks!
Dawid

**Comment by theron-wang** [comment]
Thanks for letting me know! ARM should be supported in 1.2.4. I haven't been able to test it, however, since I don't own a computer which supports the ARM version. If there are any issues, please let me know!

**Comment by dchelstowski** [comment]
sure will do so, when I will have some spare time, definitelly! thanks!

**Comment by theron-wang** [comment]
Great! Thanks for letting me know!
