### ISSUE TITLE
Not working for tsx files

### ISSUE THREAD

**Issue by mcapodici** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#41]
With this tailwind config:

```
/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {},
    },
    plugins: [],
}

```

The plugin works for the html file but not the .tsx files. By not work, I mean that it wont suggest classes, whether using "class" or "className". It does work on the index.html, which proves it is working to some extent.

**Comment by theron-wang** [comment]
Unfortunately, Visual Studio doesn’t allow extensions to override HTML IntelliSense in `.tsx` and `.jsx` files. If VS eventually adds support or if I find another solution, I will be sure to let you know. Sorry about this!

**Comment by mcapodici** [comment]
Ah I see, that is a annoying. Thanks for creating the extension though, it is very useful.

**Comment by theron-wang** [comment]
I did find a solution to this issue - `jsx` and `tsx` files should now have support in 1.4.0. Glad to hear that you find the extension useful!

**Comment by mcapodici** [comment]
Nice, thanks for fixing!
