### ISSUE TITLE
Allow the configuration file to have other extensions

### ISSUE THREAD

**Issue by Timonney** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#44]
My config file as a "cjs" extension (tailwind.config,cjs) so I can't set it as a config file

Is it possible to add this kind of extension for the config file ?

**Comment by theron-wang** [comment]
In this case, you could change the relative path of the configuration file
(ConfigurationFile property) in your tailwind.extension.json file. I will
definitely add context menu support in the near future, though; thanks for
letting me know.

**Comment by theron-wang** [comment]
Added in 1.4.1

**Comment by Timonney** [comment]
thank you
