### ISSUE TITLE
[Feature request] Keep "Sort tailwind classes" actions visible in Tools menu (if we sort manually)

### ISSUE THREAD

**Issue by RemiCELLARD** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#45]
Hi,

I would like to know if we can keep these options when we wan't to sort the css classes OnSave or OnBuild of the opened files ? 
( create a new option in the class sorting parameters called “Manual” ? )
- Sort tailwind classes in current file
- Sort tailwind classes in solution

![image](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/25703106/18ef774e-c7ee-4442-9867-5852570e42c6)

Because, when I set the option to None, it removes both options from the Tools menu.

Thanks

**Comment by theron-wang** [comment]
Resolved with #48
