### ISSUE TITLE
[Feature request] Define a folder instead of a single css file built with Tailwind

### ISSUE THREAD

**Issue by RemiCELLARD** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#46]
Hi,

I would like to know if we can add an extra parameter in the `tailwind.extension.json` file to configure an input folder and an output folder to build ?
Also, is it possible to define a list of files instead of a single one in the `InputCssFile` and `OutputCssFile` fields?

Example:

```json
{
    "ConfigurationFile":"tailwind\\tailwind.config.js",
    "InputCssFile": ["Tailwind\\css\\tailwind.css","Tailwind\\css\\secondfile.css"],
    "OutputCssFile":["wwwroot\\css\\tailwind.css","wwwroot\\css\\secondfile.css"],
    "UseCli":false
}
```

Thanks

**Comment by theron-wang** [comment]
Sorry about the delay. I'll try to get around to it soon - I'm still not too sure on how the best way to implement this is. The problem with using a list is that the context menu behavior would be inconsistent, but I am thinking that users can define a path template for output files (maybe, for each file, define a special folder for output/make the output file `{name}.output.css`?)

**Comment by theron-wang** [comment]
@RemiCELLARD Just added in 1.5.0; I opted for a new `tailwind.extension.json` format and deprecated the original `InputCssFile` and `OutputCssFile`, replacing it with `BuildFiles`. Here's a sample:

```json
{
  "ConfigurationFile":"tailwind.config.js",
  "BuildFiles": [
    {
      "Input": "other.css",
      "Output": "other.output.css"
    },
    {
      "Input": "other2.css",
      "Output": "other2.output.css"
    }
  ],
  "UseCli": false
}
```

If you think there should be any changes, please feel free to let me know.
