### ISSUE TITLE
 [Feature request] Define another location for package.json and package-lock.json files

### ISSUE THREAD

**Issue by RemiCELLARD** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#47]
Hello,

I'd like to know if it's possible to add an extra parameter in the `tailwind.extension.json` file to configure the location of the `package.json` file?
In the extension code, this is referenced according to the location of the `tailwind.config.js` file. However, my `tailwind.config.js` file is in a different directory from the `package.json` file.

Example:
```json
{
"TailwindConfigurationFile":"tailwind\\tailwind.config.js",
"PackageConfigurationFile":"package.json",
"InputCssFile":null,
"OutputCssFile":null,
"UseCli":false
}
```

Thank you

**Comment by theron-wang** [comment]
Added in 1.4.1; thanks for the suggestion!
