### ISSUE TITLE
[Build type] Reintroduce Build OnSave

### ISSUE THREAD

**Issue by RemiCELLARD** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#50]
Hi,

Since the v1.4.2 update, the `OnSave` value has been removed from the parameter `Build type`.
When we build with custom build, we can't relaunch it when we save a file (especially when launching hot reloads with Blazor).

Can we reintroduce the OnSave concept for custom builds ?

In my case, I have this command:
```
"build-css": "npx postcss ./Tailwind/css --base ./Tailwind/css --dir ./wwwroot/css --watch --verbose --poll --no-map --ext --config ./Tailwind/postcss.config.js",
```

Thanks

**Comment by theron-wang** [comment]
My apologies - I did not foresee that being an issue. I will be sure to re-add the feature in the next release.

**Comment by theron-wang** [comment]
Added in 1.4.3
