### ISSUE TITLE
Nextjs app router

### ISSUE THREAD

**Issue by Santu-Santra9679809523** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#51]
The extension is outstanding; however, it encounters issues when integrating Tailwind CSS with a Next.js application during its creation.  If the issue originates from my side, I would appreciate guidance or a resolution to this matter. Thank you.

**Comment by theron-wang** [comment]
@Santu-Santra9679809523 What type of issues are you encountering? Are certain features broken or are there exceptions being raised? If there are any errors, they should be logged to the 'Extensions' output window (click the dropdown menu for the Build output window). Also, if you could provide steps to reproduce the issue, that would be greatly appreciated. Thank you!

**Comment by theron-wang** [comment]
I'm going to close this issue for now - if you still encounter this issue, feel free to either mention me or re-open this issue.
