### ISSUE TITLE
[Feature request] Automatically add config files to the project

### ISSUE THREAD

**Issue by jan-franek** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#52]
Hi,
would it be possible to automatically add the "tailwind.config.js" and "tailwind.extension.json" files created via the "Set up and install Tailwind CSS" and "Set up Tailwind CSS (use CLI)" commands to the project?

Thanks

**Comment by theron-wang** [comment]
Should be added in 1.4.4. Thanks for the suggestion!
