### ISSUE TITLE
Error message when removing double quotes from the class attribute

### ISSUE THREAD

**Issue by jan-franek** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#54]
When you have a class attribute, for example:
`<div class="col-start-2">some content</div>`
and remove either the first double quote or you select the second double quote with some text before it you get "Microsoft Visual Studio error" - "Object reference not set to an instance off an object".
This happens every time on Visual Studio 2022 17.9.6

**Comment by theron-wang** [comment]
> and remove either the first double quote or you select the second double quote with some text before it you get "Microsoft Visual Studio error" - "Object reference not set to an instance off an object".

I wasn't able to reproduce this exact error, but an `ArgumentOutOfRangeException` also occurred with the same behavior. That error is fixed in 1.4.4, but I'm not sure about this exception. If this issue persists, could you provide the file type and full file (if possible)? Thanks.

**Comment by theron-wang** [comment]
If you still encounter this issue, feel free to let me know or just re-open this issue!
