### ISSUE TITLE
Improve message when having conflicting tailwind classes

### ISSUE THREAD

**Issue by skttl** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#55]
When having conflicting tailwind classes, it would be awesome if it could show which of the classes are being overwritten.

![image](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/3726467/acaed7b9-84ff-463d-81e2-276fd57326e7)

E.g. in this example, flex has no effect, because inline-flex comes after flex in the build output from Tailwind.

IIRC, the order of properties in your tailwind config defines which one wins (last one wins).

Could also even be just flex that would have the squigglies.

**Comment by theron-wang** [comment]
I've added a small note which tells you which (if the extension can find it) class takes precedence over another. For example, the message in the picture will also say that flex's styles override inline-flex. Thank you for the suggestion!
