### ISSUE TITLE
Set File Version for the extension assembly

### ISSUE THREAD

**Issue by AmadeusW** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#56]
Recently you've fixed a COMException caused by UI thread dependency of a COMObject in the MEF part constructor: [291bee47](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/commit/291bee477c36977097df34122d76791272a90226)

I work on Visual Studio and I've worked around this crash by excluding this extension from preloading on BG thread. (Preloading reduces UI delays on startup). We'd like to restore capability to preload this extension on BG thread. To detect that developer is using fixed version, we're using the `System.Diagnostics.FileVersionInfo.GetVersionInfo(pathToTailwindCSSIntellisenseDll)`

However, this version is unset regardless of release (shows as `1.0.0.0`):
![image](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/1673956/b7db5416-9c3f-4da7-8419-36047ae8f306)

Would it be OK to set the file version to match the extension version (e.g. `1.4.4`) so that we can remove this extension from the exclusion list?

**Comment by theron-wang** [comment]
First off, thank you for your work on Visual Studio!

I set the assembly file version to `1.4.5` in the latest release. Going forward, I will continue to keep the assembly and extension versions consistent. If the issue arises again, please let me know so I can come out with a fix.
