### ISSUE TITLE
Custom build : The system cannot find the path specified.

### ISSUE THREAD

**Issue by RemiCELLARD** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#58]
Hi,
In this kind of configuration, the extension return an error => The system cannot find the path specified.

Configuration : 
![image](https://github.com/user-attachments/assets/247c8476-7cad-4fce-b78b-82f98b0e68c6)

tailwind.extension.json : 
```
{
  "ConfigurationFile": "Tailwind\\tailwind.config.js",
  "InputCssFile": "Tailwind\\css\\tailwind.css",
  "OutputCssFile": "wwwroot\\css\\tailwind.css",
  "PackageConfigurationFile": "package.json",
  "UseCli": false
}
```

Project structure : 
![image](https://github.com/user-attachments/assets/7a1394ee-64ca-4982-9b84-0618b88795bb)

System used : Windows 11

**Comment by RemiCELLARD** [comment]
It would seem that it is this command execution that causes the exception to be raised.

https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/blob/6ebd25c69dc6c0ba6d0f3dd079a3e87cfc622433/src/Build/TailwindBuildProcess.cs#L214

**Comment by alex-jitbit** [comment]
Have the same problem

**Comment by theron-wang** [comment]
Thanks for the fix! I'll probably include this in a release (1.4.6) either today/tomorrow when I get around to fixing #57.
