### ISSUE TITLE
[Feature Request] ASP.NET Web Forms IntelliSense Support

### ISSUE THREAD

**Issue by Lepidopteran** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#6]
This is a great extension, thank you for creating it! However I've noticed you don't have IntelliSense for ASP.NET web forms. The common file extension types are "aspx, ascx, and master". Could you please consider adding this feature? Thank you!

**Comment by theron-wang** [comment]
I'm glad you like the extension! 

As for your suggestion, I've added support for web forms files. I just published an update for the extension, so you can check that out. 

Thanks!

**Comment by Lepidopteran** [comment]
Thank you very much, ill check it out!
