### ISSUE TITLE
[Feature request] Add a configuration field to choose which file extensions launch the CSS build on backup.

### ISSUE THREAD

**Issue by RemiCELLARD** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#60]
Today : 
The file extensions that launch the CSS build execution on saving are hard-coded in the TailwindBuildProcess.cs file.

https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/blob/5b0ab3fc279a3406dd86956bc399db7de5d11904/src/Build/TailwindBuildProcess.cs#L145-L151

Idea : 
- Add a configuration field to choose which file extensions launch the CSS build on backup (if *Build Type => OnSave* is selected)
- Use a separator (e.g. the ; character) for each file extension to launch the event.

---

- [x] I'll create a pull request for this.

**Comment by theron-wang** [comment]
Thanks :). I'll create a release for this later (and close this issue when I do).

**Comment by theron-wang** [comment]
Released in 1.4.6.
