### ISSUE TITLE
[Bug] Not all added get colors parsed in Intillisense

### ISSUE THREAD

**Issue by djbist** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#62]
Hi there,
I'm having trouble hinting at my color classes when they have more categories in the tree.

![image](https://github.com/user-attachments/assets/484732d0-47d4-42fb-9a76-70c098ae2b91)

![image](https://github.com/user-attachments/assets/564ae6cf-49a6-4ee6-98c8-79af55d0a671)

![image](https://github.com/user-attachments/assets/c01930b0-bba7-4bf3-9c12-bec8bf800049)

All these colors work in the design, but they are not in the tooltips and as you can see, they do not "color the squares".

Am I doing something wrong?

**Comment by djbist** [comment]
This solution works, but it is not very intuitive to create.


![image](https://github.com/user-attachments/assets/b9bad803-76ce-4f23-b8bc-54908bff05cd)

![image](https://github.com/user-attachments/assets/f0517aa2-d69e-4b84-9892-6f5e85c34e5e)

**Comment by theron-wang** [comment]
Hmm, definitely a bug with the extension. I’ll take a look at this and hopefully release a fix soon. Thanks :)

**Comment by theron-wang** [comment]
The extension previously only supported nesting _directly_ under `colors`, so any further colors (i.e. `sterowanie.green.light`) were not parsed. This should be fixed in 1.4.7!
