### ISSUE TITLE
Bug: @apply with !important results in an error

### ISSUE THREAD

**Issue by camwar11** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#63]
Using `@apply` with `!important` results in `!important` being sorted in front of CSS classes and a CssSyntaxError: "The `!important` class does not exist. If `!important` is a custom class, make sure it is defined within a `@layer` directive."

To reproduce:

Add a rule to a .css file like:
```CSS
.my-class {
    @apply bg-white !important;
}
```
Save or manually have the extension sort the .css file, which results in:
```CSS
.my-class {
    @apply !important bg-white;
}
```

**Comment by theron-wang** [comment]
Yep, thanks! This should be fixed in 1.4.7.
