### ISSUE TITLE
color scale appears to be inverted

### ISSUE THREAD

**Issue by Nicolas-Labbe** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#64]
![Screenshot_1](https://github.com/user-attachments/assets/75a710af-73de-4185-9244-fab3f9aa1f84)

When using the text- or bg-, the color scale appears to be inverted. Specifically, lower numbers (e.g., text-red-50) should represent lighter colors, and higher numbers (e.g., text-red-800) should represent darker colors. However, in my case, the lower numbers are displaying darker colors, and the higher numbers are displaying lighter colors.

**Comment by theron-wang** [comment]
@Nicolas-Labbe Thanks for reporting - I wasn't able to reproduce the issue in my editor (VS Community v17.1.1), but I changed some code which may fix it. Basically, VS tries to invert colors when dark mode is active, and a [pixel needs to be added to the resulting image](https://stackoverflow.com/questions/37663993/preventing-icon-color-and-size-distortions-when-bundling-a-visual-studio-project) (in this case, the individual colors) to prevent this behavior. In your case, the pixel might have been added in an incorrect location, causing these inverted colors.

If this issue still isn't resolved, please let me know your VS version and what themes you are using, if any. If it's resolved, great - feel free to close this!

**Comment by Nicolas-Labbe** [comment]
![image](https://github.com/user-attachments/assets/c6ec6651-ecba-447b-a9aa-3a18d1b74e8b)

working like a charm! thanks you
