### ISSUE TITLE
IntelliSense - blocklist is not taken into consideration

### ISSUE THREAD

**Issue by v36u** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#69]
Even if I add `container` in the blocklist, as in the [official documentation](https://tailwindcss.com/docs/content-configuration#discarding-classes), IntelliSense still suggests it

**Comment by v36u** [comment]
Same thing if I disable it as a core plugin:
```
  corePlugins: {
    container: false,
  },
```

**Comment by theron-wang** [comment]
Thanks! This should be added in 1.5.5.
