### ISSUE TITLE
Lag in text-editor

### ISSUE THREAD

**Issue by djbist** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#72]
The extension has been causing lag in the text editor for several weeks. In ver 1.4.x I didn't notice this problem. When I turn extension off I don't have any problem with lag. Any ideas? :(

**Comment by theron-wang** [comment]
@djbist Thanks for letting me know! Was lag occurring when typing any specific classes (i.e. there was an issue in the past when typing transparency values like `bg-green-50/10`) or in any specific files? I'll definitely take a look into this - I was refactoring code in recent updates so I may have accidentally introduced some lag somewhere.

**Comment by djbist** [comment]
Hi! The delay happens all the time, no matter if you're writing a tag, a class, or plain text. I noticed it mainly in *.cshtml *.css files, it does not appear in *.js files, or at least I didn't notice it. The more lines, the more frequent and longer the lag.

**Comment by theron-wang** [comment]
> I noticed it mainly in *.cshtml *.css files, it does not appear in *.js files, or at least I didn't notice it.

@djbist Thanks for the clarification! I did try testing and profiling this, but I couldn't find any performance lags (typical lag was measured to be around 100-150ms for typing in debug mode, release should be faster). The file I used was medium-sized, ~20k characters. Is it possible for you to send a file that lags? If not, that's fine - I would appreciate it if you could let me know roughly how large the file is so I can better reproduce the lag.

**Comment by djbist** [comment]
[](url)

https://github.com/user-attachments/assets/db17a8fd-419a-4cf0-a300-b4d476f9aad7

The file itself won't help much as it is part of the entire project. The problem occurs when IIS Express is running. The attached video shows the reaction to backspace when the plugin is running. Without a plug-in, the response is "instantaneous", without delay. The delay, although slightly smaller, also appears in an almost empty file.

**Comment by theron-wang** [comment]
Thanks! It looks like you are using the Legacy Razor editor, in which I was able to reproduce the error as shown in the video. I am currently working on a fix - at the moment, you can use the new Razor editor if you need the extension to work.

**Comment by djbist** [comment]
Thanks a lot! It's workin'! I had no idea I had 'true' checked for legacy razor editor. Thanks and have a good day! (It's 8:30 am for me xD) :)

**Comment by theron-wang** [comment]
No problem. Glad to hear that it works!
