### ISSUE TITLE
IntelliSense for variable values

### ISSUE THREAD

**Issue by v36u** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#73]
```razor
<div class="row mt-5">
  <div class="md:col-4">
    @{
      var testClass = "mb-3";
    }
    <p class="@testClass"></p>
  </div>
</div>
```

For the above example, there are no IntelliSense suggestions for the value assigned to `testClass`.

I think adding IntelliSense support for values of variables with names ending with `[Cc]lass[es]` would improve DX. Please also make it support reassignment, e.g.:
```razor
<div class="row mt-5">
  <div class="md:col-4">
    @{
      var testClass = "mb-3";
      
      if (a > b) 
      {
        testClass = "pt-2";
      }
    }
    <p class="@testClass"></p>
  </div>
</div>
```

**Comment by theron-wang** [comment]
Added in 1.5.6. Currently, it only supports IntelliSense: class sorting and linting will take a significant rewrite that I'm not able to do at the moment; I will definitely work on that in the future, however. Thanks for the suggestion!
