### ISSUE TITLE
Color preview

### ISSUE THREAD

**Issue by v36u** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#74]
I would love to see the color previews as small squares next to the class names that are used for coloring (e.g., `text-green-500`, `bg-primary` (custom), `border-purple-200`).

Concrete example of what I'm thinking of: https://github.com/MadsKristensen/EditorColorPreview

**Comment by theron-wang** [comment]
Added in 1.5.6. Thanks :)

**Comment by v36u** [comment]
Thank you very much!

One bug I've noticed so far: the color preview does not work for classes that have special rules, such as `hover:bg-green-500`, `active:text-purple-100`

**Comment by theron-wang** [comment]
Sorry about that oversight - this should be fixed in 1.6.1. Thanks!
