### ISSUE TITLE
Custom class name completion contexts

### ISSUE THREAD

**Issue by DennisRosen** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#79]
It would be great if the extension could handle custom class name completion contexts, similar to how it works for the vs code tailwind extension. In vs code custom contexts can be added as regexes using the `tailwindCSS.experimental.classRegex` property.

For example:

```
<input 
    class="@(
        string.Join(" ", new [] {
            "w-full px-md py-sm text-t-neutral-700",
            "outline-none focus:outline-none focus-visible:outline-none"
        })
    )"
    ...
/>
```

At the moment the extension's intellisense does not work with the above.

**Comment by theron-wang** [comment]
I will definitely look into adding this in the future. At the moment, this extension is written in a way that wouldn't work with a regex system like the official extension, so it will need a significant rewrite to add this functionality.

If you want IntelliSense for these contexts at the moment, I believe (but did not confirm) that you can add a comment on the line before each string with `class=`:

```razor
<input 
    class="@(
        string.Join(" ", new [] {
            // class=
            "w-full px-md py-sm text-t-neutral-700",
            // class=
            "outline-none focus:outline-none focus-visible:outline-none"
        })
    )"
    ...
/>
```

**Comment by theron-wang** [comment]
@DennisRosen Sorry about the delay; this functionality should be added in 1.7.0. For specific guidelines regarding custom regexes, you can check out `Getting-Started.md`. Please let me know if you run into any issues!

`Getting-Started.md`:

Custom regexes can be defined in settings. Please note that:

- There can only be one, valid C# regex.
- Your class content must be located in the content capture group. For example, the regex class="(?<content>.*)" successfully captures content.
- Custom regexes take precedence over default functionality; that is, if a context is matched in both your custom regex and the original regex, the custom regex will be used.
- It's recommended to thoroughly test your regexes before adding it into your options. Unintended behavior may occur if the regex is too general or if it overlaps with existing functionality.
