### ISSUE TITLE
Intellisense for colors does not work correctly with tailwind prefix

### ISSUE THREAD

**Issue by DennisRosen** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#80]
As per the title, adding a prefix to `tailwind.config.js` makes searching for color classes via intellisense rather iffy.

For example, having the prefix `tw-` and a color `red` inside the config: 

- If you start typing `tw-text-r` then the intellisense search fails to find the class `tw-text-red`. 
- However, if you start to type `text-r` then the search will find and highlight the class `tw-text-red`.

Same happens with other color properties like `bg-`, `fill-` etc.
Not sure if more tailwind properties are affected - colors are the one I found so far.

**Comment by theron-wang** [comment]
Thanks :). This should be fixed in 1.6.4.
