### ISSUE TITLE
Question: data storage

### ISSUE THREAD

**Issue by pm64** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#81]
Just a quick question about this excellent extension. When I right-click a Tailwind CSS config file in Solution Explorer, and click "Set as Tailwind CSS configuration file", where does the extension store that information?

Also, for this extension to start, must the config file be in the root directory of a project, or can it be buried in a subdirectory?

Thanks for this project!

**Comment by theron-wang** [comment]
> When I right-click a Tailwind CSS config file in Solution Explorer, and click "Set as Tailwind CSS configuration file", where does the extension store that information?

There is a JSON file (`tailwind.extension.json`) in the project that contains your configuration file. It should always be located in the base directory of the project.

> Also, for this extension to start, must the config file be in the root directory of a project, or can it be buried in a subdirectory?

The config file can be located in any subdirectory, as long as it's named `tailwind.config.js`. If, for some reason, the extension can't find it, then you can explicitly set its location in the `tailwind.extension.json` file (or by right-clicking on your config file).

> Thanks for this project!

No problem, I'm glad that you like it :)

**Comment by pm64** [comment]
@theron-wang thank you for the explanation, but this isn't consistent with what I'm seeing.

In my case, my project has a "Styles" subdirectory that includes tailwind.config.js and my input file, app.css.

If I right-click tailwind.config.js and select "Set as Tailwind CSS configuration file", I expect the tailwind.extension.json file to be created in the base directory of my project (the directory containing the .csproj file).

However, no such file is created.

After this, the option changes to "Remove as Tailwind CSS configuration file", so the extension does seem to be aware of the current state. But I can't locate tailwind.config.js in the project or solution directory, the "Styles" subdirectory, or anywhere.

**Comment by theron-wang** [comment]
Does this state persist across sessions, or do you have to reset the config file every time you reopen the editor?

I reviewed my code, and found that it’s also possible that the `tailwind.extension.json` file is in the base directory of any project. At the moment, if no `tailwind.config.js` file is in the root directory, the extension chooses the first project to save settings in. I would check to see if any other projects have the file; if so, you can simply move it to the base directory of your Tailwind project and it should continue to work (though you may need to restart VS). 

I’ll make some adjustments later so the `tailwind.extension.json` file is saved in the project of the set configuration file. Thanks!

**Comment by theron-wang** [comment]
@pm64 Sorry about the delay. 1.7.0 should now make `tailwind.extension.json` automatically move itself to the project base of the set configuration file. If you have any other concerns, please let me know!
