### ISSUE TITLE
The 'Build Tailwind Css' is not working

### ISSUE THREAD

**Issue by VETWorks** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#82]
I installed the plugin, node, npm. Added tailwind, initialised tailwind and got all the files needed. Set the input / output css, edited the config file, added postcss config file.

When I run `npx tailwindcss -i tailwind.input.css -o Content\\css\\app-tailwind.css` everything works fine. The "app-tailwind.css" is being created and the website works.

When selecting "Build Tailwind CSS" nothing happens. The log says:

```
16:40:57:442	Tailwind CSS: Build started...
16:40:57:838	Tailwind CSS: Build stopped (0 processes left)
```

The output css is not changed or updated. If I clear it, it stays empty.

What could be the reason? The output log for "Extensions" is empty and also in the Build log there is no error. Just `Tailwind CSS: Build stopped`

My `tailwind.config.js`:

```
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./Views/**/*.{js,cshtml,html}", "./node_modules/flowbite/**/*.js"],
    darkMode: 'class',
    theme: {
       extend: {},
    },
    plugins: [
        require('flowbite/plugin')
    ],
}
```

My `tailwind.extension.json`:

```
{"ConfigurationFile":"tailwind.config.js","BuildFiles":[{"Input":"tailwind.input.css","Output":"Content\\css\\app-tailwind.css"}],"UseCli":false}
```

**Comment by theron-wang** [comment]
Thanks for reporting! I was not able to reproduce this behavior, however, but I suspect that it may relate to pathing based on the information you provided. I implemented a potential fix in 1.6.4, which uses relative paths instead of absolute paths (as it was previously), so the build command ran by the extension should match the one you ran manually. I also added a verbose build option (toggle it in Tools > Options > Tailwind CSS IntelliSense > Build > Verbose builds), which you can toggle to provide some more information in case your issue still isn't fixed.

**Comment by Nicolas-Labbe** [comment]
I'm experiencing the same issue; it only works when I create a custom build, whereas it used to work fine without needing one. I am currently using Visual Studio 2022, version 17.11.5.

Here's the log output when I run Tailwind:

```
Tailwind CSS: Building... 
Tailwind CSS: Build started...
Tailwind CSS: The system cannot find the specified path.
Tailwind CSS: > build:css
Tailwind CSS: > npx tailwindcss -i ./wwwroot/css/tailwind.css -o ./wwwroot/css/tailwind.min.css --minify
Tailwind CSS: Rebuilding...
Tailwind CSS: Done in 3788ms.
```

And here’s the log output without the custom build:

```
Tailwind CSS: Build started...
Tailwind CSS: Build stopped (0 processes left)
```

![image](https://github.com/user-attachments/assets/8d69de27-f573-4387-ac71-33256d5214c5)

**Comment by VETWorks** [comment]
Just a follow-up, the issue was resolved by setting the correct PATH parameters. 

We initially installed node through fnm using the PowerShell, but node and npm were only accessible in the same PowerShell window. Then we decided to use the normal Windows installer and everything was OK.

**Comment by theron-wang** [comment]
@Nicolas-Labbe Is this the case for you as well? It would explain the `The system cannot find the specified path.` error message in your log.
