### ISSUE TITLE
[Feature Request] Enhance intellisense spacing description to also include the value in pixels in addition to rem

### ISSUE THREAD

**Issue by gpshonik** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#9]
Would it be possible to add the tailwind **px** equivalent for the spacing utility classes? I have a hard time thinking in terms of rem relative sizing so this would make selecting the correct class even easier.  Thank you!

Example:

<img width="304" alt="image" src="https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/1524361/546432d6-3251-410c-be20-49e67bf8f1c9">

https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale

<img width="583" alt="image" src="https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/1524361/384598d2-ea2e-450b-9b19-fc3b3964e290">

**Comment by theron-wang** [comment]
I just released an update which includes this. Thanks!
